baseurl = "https://martinribelotta.github.io"
title = "Development Services"
theme = ["hugo-embed-pdf-shortcode", "hugo-coder"]
languagecode = "en"
defaultcontentlanguage = "en"
enableInlineShortcodes = true
tableOfContents = true

[pagination]
  pagerSize = 20

# disqusShortname = "yourdiscussshortname"

[services]
  [services.googleAnalytics]
    ID = 'G-E962FFEWTP'

[markup]
  defaultMarkdownHandler = 'goldmark'

[markup.goldmark.renderer]
  hardWraps = true
  unsafe = true
  xhtml = true

[markup.tableOfContents]
  endLevel = 3
  ordered = false
  startLevel = 2

[markup.highlight]
  style = "github-dark"

[params]
  author = "Martin Ribelotta"
  info = "Embedded Developer and Electronics Specialist"
  description = "Martin Ribelotta's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/images/favicon.svg"
  favicon_32 = "/images/favicon-32x32.png"
  favicon_16 = "/images/favicon-16x16.png"

  since = 2024

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "WhatsApp"
  icon = "fa-brands fa-whatsapp fa-2x"
  weight = 1
  target = "_blank"
  url = "https://wa.me/5492944640761?text=Hello%2C%20Martin%21%20I%20am%20contacting%20you%20from%20your%20website%20homepage."
  desc = "Chat with me on WhatsApp"
[[params.social]]
  name = "mailto"
  icon = "fa fa-envelope fa-2x"
  weight = 2
  target = "_blank"
  url = "mailto:martinribelotta@gmail.com?subject=Hello%2C%20Martin%21%20I%20am%20contacting%20you%20from%20your%20website%20homepage."
  desc = "Ask a question directly to my mail"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 3
  target = "_blank"
  url = "https://www.linkedin.com/in/martin-ribelotta/"
  desc = "View my profile on LinkedIn"
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 4
  target = "_blank"
  url = "https://github.com/martinribelotta/"
  desc = "Explore my public projects on github"
[[params.social]]
  name = "Gitlab"
  icon = "fa-brands fa-gitlab fa-2x"
  weight = 5
  target = "_blank"
  url = "https://gitlab.com/martinribelotta/"
  desc = "Explore my public projects on gitlab"
[[params.social]]
  name = "Instagram"
  icon = "fa-brands fa-instagram fa-2x"
  weight = 6
  target = "_blank"
  url = "https://www.instagram.com/martin.ribelotta.engineering/"
  desc = "View my profile on Instagram"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"
[[menu.main]]
  name = "Curriculum"
  weight = 2
  url = "cv/"
[[menu.main]]
  name = "Projects"
  weight = 3
  url = "projects/"
[[menu.main]]
  name = "Blog"
  weight = 4
  url  = "posts/"
[[menu.main]]
  name = "Contact"
  weight = 5
  url = "contact/"
